import { sql } from 'drizzle-orm';
import { boolean, date, index, integer, jsonb, numeric, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import type { InferInsertModel, InferSelectModel } from 'drizzle-orm';

import { organizations, users } from './baseline.js';

export const product = pgTable(
  'product',
  {
    productCode: text('product_code').primaryKey(),
    productName: text('product_name'),
    packSize: text('pack_size'),
    numberOfCases: numeric('number_of_cases'),
    recipeComponents: text('recipe_components'),
    ingredientCodes: text('ingredient_codes'),
    template: text('template'),
    closedCore: text('closed_core'),
    primaryIngredientPct: numeric('primary_ingredient_pct'),
    runsPerWeek: numeric('runs_per_week'),
    dateCodePerWeek: text('date_code_per_week'),
    closedPlanning: text('closed_planning'),
    launchDate: date('launch_date'),
    departmentNumber: text('department_number'),
    articleNumber: text('article_number'),
    barCodes: text('bar_codes'),
    casesPerWeekW1: numeric('cases_per_week_w1'),
    casesPerWeekW2: numeric('cases_per_week_w2'),
    casesPerWeekW3: numeric('cases_per_week_w3'),
    closedCommercial: text('closed_commercial'),
    process1: text('process_1'),
    yieldP1: numeric('yield_p1'),
    process2: text('process_2'),
    yieldP2: numeric('yield_p2'),
    process3: text('process_3'),
    yieldP3: numeric('yield_p3'),
    process4: text('process_4'),
    yieldP4: numeric('yield_p4'),
    line: text('line'),
    dieset: text('dieset'),
    yieldLine: numeric('yield_line'),
    staffing: text('staffing'),
    rate: numeric('rate'),
    prCodeP1: text('pr_code_p1'),
    prCodeP2: text('pr_code_p2'),
    prCodeP3: text('pr_code_p3'),
    prCodeP4: text('pr_code_p4'),
    prCodeFinal: text('pr_code_final'),
    closedProduction: text('closed_production'),
    shelfLife: text('shelf_life'),
    closedTechnical: text('closed_technical'),
    box: text('box'),
    topLabel: text('top_label'),
    bottomLabel: text('bottom_label'),
    web: text('web'),
    mrpBox: text('mrp_box'),
    mrpLabels: text('mrp_labels'),
    mrpFilms: text('mrp_films'),
    mrpSleeves: text('mrp_sleeves'),
    mrpCartons: text('mrp_cartons'),
    taraWeight: numeric('tara_weight'),
    palletStackingPlan: text('pallet_stacking_plan'),
    boxDimensions: text('box_dimensions'),
    closedMrp: text('closed_mrp'),
    price: numeric('price'),
    leadTime: numeric('lead_time'),
    supplier: text('supplier'),
    procShelfLife: numeric('proc_shelf_life'),
    closedProcurement: text('closed_procurement'),
    doneCore: boolean('done_core'),
    donePlanning: boolean('done_planning'),
    doneCommercial: boolean('done_commercial'),
    doneProduction: boolean('done_production'),
    doneTechnical: boolean('done_technical'),
    doneMrp: boolean('done_mrp'),
    doneProcurement: boolean('done_procurement'),
    statusOverall: text('status_overall'),
    daysToLaunch: integer('days_to_launch'),
    built: boolean('built').notNull().default(false),
    orgId: uuid('org_id')
      .notNull()
      .references(() => organizations.id),
    extJsonb: jsonb('ext_jsonb').notNull().default({}),
    privateJsonb: jsonb('private_jsonb').notNull().default({}),
    schemaVersion: integer('schema_version').notNull().default(1),
    modelPredictionId: uuid('model_prediction_id'),
    epcisEventId: uuid('epcis_event_id'),
    externalId: text('external_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    createdByUser: uuid('created_by_user')
      .notNull()
      .references(() => users.id),
    createdByDevice: text('created_by_device'),
    appVersion: text('app_version'),
  },
  (table) => ({
    orgStatusDaysIdx: index('product_org_status_days_idx').on(table.orgId, table.statusOverall, table.daysToLaunch),
    orgLaunchUnbuiltIdx: index('product_org_launch_unbuilt_idx')
      .on(table.orgId, table.launchDate)
      .where(sql`built = false`),
  }),
);

export type Product = InferSelectModel<typeof product>;
export type NewProduct = InferInsertModel<typeof product>;
