-- Migration 137: T-033 legacy brief_to_fa_audit compatibility audit.
-- Canonical behavior is Brief -> Project completion; FA is a legacy alias.
-- Wave0 lock: org_id business scope (NOT tenant_id); RLS via app.current_org_id().

create table if not exists public.brief_to_fa_audit (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  brief_id uuid not null,
  product_code text,
  field_name text not null,
  applied boolean not null default false,
  mapping_version integer not null default 1,
  created_at timestamptz not null default now(),
  constraint brief_to_fa_audit_brief_org_fkey
    foreign key (brief_id, org_id) references public.brief(brief_id, org_id) on delete cascade,
  constraint brief_to_fa_audit_brief_field_unique unique (brief_id, field_name),
  constraint brief_to_fa_audit_field_name_check check (
    field_name ~ '^C([1-9]|1[0-9]|20)$'
  ),
  constraint brief_to_fa_audit_mapping_version_check check (mapping_version >= 1)
);

create index if not exists brief_to_fa_audit_org_brief_idx
  on public.brief_to_fa_audit (org_id, brief_id);

alter table public.brief_to_fa_audit enable row level security;
alter table public.brief_to_fa_audit force row level security;

drop policy if exists brief_to_fa_audit_org_context on public.brief_to_fa_audit;
create policy brief_to_fa_audit_org_context
  on public.brief_to_fa_audit
  for all
  to app_user
  using (org_id = app.current_org_id())
  with check (org_id = app.current_org_id());

revoke all on public.brief_to_fa_audit from public;
revoke all on public.brief_to_fa_audit from app_user;
grant select, insert, update, delete on public.brief_to_fa_audit to app_user;
grant usage, select on sequence public.brief_to_fa_audit_id_seq to app_user;

comment on table public.brief_to_fa_audit
  is 'T-033 legacy compatibility audit for Brief -> Project completion. FA/Product creation remains owned by G3.';

alter table public.outbox_events drop constraint if exists outbox_events_event_type_check;
alter table public.outbox_events add constraint outbox_events_event_type_check check (
    event_type in (
      'audit.recorded',
      'bom.initial_version_created',
      'bom.version_submitted',
      'brief.completed_for_project',
      'brief.converted',
      'brief.created',
      'compliance_doc.deleted',
      'compliance_doc.expired',
      'compliance_doc.expiring',
      'compliance_doc.uploaded',
      'd365.cache.refreshed',
      'fa.allergens_changed',
      'fa.built',
      'fa.built_reset',
      'fa.cascade',
      'fa.core_closed',
      'fa.created',
      'fa.deleted',
      'fa.dept_closed',
      'fa.intermediate_code_changed',
      'fa.recipe_changed',
      'fa.template_applied',
      'fg.allergens_changed',
      'fg.bom.released',
      'fg.created',
      'fg.intermediate_code_changed',
      'fg.release_blocked',
      'fg.released_to_factory',
      'formulation.locked',
      'formulation.submitted_for_trial',
      'lp.received',
      'npd.builder.released_records_created',
      'npd.project.brief_mapped',
      'npd.project.created',
      'npd.project.release_requested',
      'onboarding.first_wo_recorded',
      'onboarding.step.advance',
      'onboarding.step.back',
      'onboarding.step.jump',
      'onboarding.step.restart',
      'onboarding.step.skip',
      'org.created',
      'quality.recorded',
      'risk.created',
      'role.assigned',
      'rule.deployed',
      'settings.line.upserted',
      'settings.location.upserted',
      'settings.machine.upserted',
      'settings.module.toggled',
      'settings.notification_channel_updated',
      'settings.notification_digest_updated',
      'settings.notification_rule_updated',
      'settings.org.created',
      'settings.org.updated',
      'settings.reference.row_updated',
      'settings.role.assigned',
      'settings.rule.deployed',
      'settings.schema.migration_requested',
      'settings.scim.token_created',
      'settings.sso.config_changed',
      'settings.user.accepted',
      'settings.user.deactivated',
      'settings.user.invited',
      'settings.warehouse.deactivated',
      'shipment.created',
      'technical.factory_spec.approved',
      'tenant.cohort.advanced',
      'tenant.migration.run',
      'tenant.migration.run.failed',
      'user.invited',
      'wo.ready'
    )
  );

comment on constraint outbox_events_event_type_check on public.outbox_events
  is 'T-033: includes brief.completed_for_project and npd.project.brief_mapped for Brief -> Project completion.';
