-- Migration: 420-outbox-settings-user-created-with-password.sql
-- Add 'settings.user.created_with_password' to the outbox event-type CHECK.
--
-- createUserWithPassword (apps/web/actions/users/create-user-with-password.ts:352)
-- emits this event with a raw string literal that was never in the enum or the
-- CHECK. Every direct-create therefore aborted with 23514 -> the action
-- compensated by deleting the fresh auth user and returned persistence_failed.
-- This is the ROOT CAUSE of the "silent user-create no-op" first seen in the
-- F3 CRUD walk and reproduced (now loudly) in the F4 live-E3.
--
-- Change summary: +1 value ('settings.user.created_with_password'), -0 values.
-- The enum gains the matching member; the drift gate pins this file's IN-list.
--
-- DRAFT applied by the orchestrator.

alter table public.outbox_events
  drop constraint if exists outbox_events_event_type_check;

alter table public.outbox_events
  add constraint outbox_events_event_type_check check (
    event_type in (
      'audit.recorded',
      'bom.initial_version_created',
      'bom.version_submitted',
      'brief.completed_for_project',
      'brief.converted',
      'brief.created',
      'catch_weight.variance_exceeded',
      'compliance_doc.deleted',
      'compliance_doc.expired',
      'compliance_doc.expiring',
      'compliance_doc.uploaded',
      'd365.cache.refreshed',
      'fa.allergens_changed',
      'fa.built',
      'fa.built_reset',
      'fa.cascade',
      'fa.core_closed',
      'fa.created',
      'fa.deleted',
      'fa.dept_closed',
      'fa.dept_reopened',
      'fa.edit',
      'fa.intermediate_code_changed',
      'fa.recipe_changed',
      'fa.template_applied',
      'fg.allergens_changed',
      'fg.bom.released',
      'fg.created',
      'fg.edit',
      'fg.intermediate_code_changed',
      'fg.release_blocked',
      'fg.released_to_factory',
      'finance.consumption.valued',
      'finance.cost_per_kg.changed',
      'finance.standard_cost.approved',
      'finance.valuation.closed_monthly',
      'finance.variance.computed',
      'formulation.locked',
      'formulation.submitted_for_trial',
      'lp.received',
      'maintenance.calibration.completed',
      'maintenance.calibration.failed',
      'maintenance.loto.applied',
      'maintenance.loto.released',
      'maintenance.mwo.completed',
      'maintenance.mwo.created',
      'maintenance.pm.due',
      'maintenance.sanitation.allergen_change.completed',
      'manufacturing_operations.created',
      'manufacturing_operations.deactivated',
      'manufacturing_operations.reset_to_seed',
      'manufacturing_operations.updated',
      'matrix.version.published',
      'npd.allergens.bulk_rebuild_completed',
      'npd.builder.released_records_created',
      'npd.fg_candidate_mapped',
      'npd.gate.advanced',
      'npd.gate.approved',
      'npd.gate.reverted',
      'npd.project.brief_mapped',
      'npd.project.created',
      'npd.project.legacy_stages_closed',
      'npd.project.release_requested',
      'oee.alert.threshold_breached',
      'oee.anomaly.detected',
      'oee.dsl_rule.updated',
      'oee.shift.aggregated',
      'oee.snapshot.refreshed',
      'onboarding.first_wo_recorded',
      'onboarding.step.advance',
      'onboarding.step.back',
      'onboarding.step.jump',
      'onboarding.step.restart',
      'onboarding.step.skip',
      'org.created',
      'org.mfa_enrollment.forced',
      'org.security_policy.updated',
      'planning.mrp.completed',
      'planning.schedule.published',
      'production.allergen_changeover.validated',
      'production.changeover.signed',
      'production.consume.blocked',
      'production.consume.completed',
      'production.downtime.recorded',
      'production.oee.snapshot',
      'production.output.recorded',
      'production.waste.recorded',
      'production.wo.closed',
      'production.wo.completed',
      'production.wo.started',
      'quality.atp_swab_failed',
      'quality.hold.created',
      'quality.hold.released',
      'quality.ncr.assigned',
      'quality.ncr.closed',
      'quality.ncr.critical_dual_signed',
      'quality.ncr.opened',
      'quality.ncr.submitted',
      'quality.ncr.updated',
      'quality.recorded',
      'reference.allergens_added_by_process.bulk_changed',
      'reference.allergens_by_rm.bulk_changed',
      'reference.csv.committed',
      'reference.row.soft_deleted',
      'reference.row.upserted',
      'reporting.export.completed',
      'reporting.export.failed',
      'reporting.mv.refresh_completed',
      'reporting.schedule.run_completed',
      'risk.created',
      'role.assigned',
      'rule.deployed',
      'scheduler.assignment.approved',
      'scheduler.assignment.bulk_approved',
      'scheduler.assignment.overridden',
      'scheduler.assignment.rejected',
      'scheduler.run.completed',
      'settings.core_flag.updated',
      'settings.d365_sync.updated',
      'settings.dept_override.updated',
      'settings.ip_allowlist.changed',
      'settings.line.upserted',
      'settings.location.deleted',
      'settings.location.imported',
      'settings.location.upserted',
      'settings.machine.upserted',
      'settings.module.disabled',
      'settings.module.enabled',
      'settings.module.toggled',
      'settings.notification_channel_updated',
      'settings.notification_digest_updated',
      'settings.notification_rule_updated',
      'settings.org.created',
      'settings.org.updated',
      'settings.reference.row_updated',
      'settings.role.assigned',
      'settings.rule.deployed',
      'settings.rule_variant.updated',
      'settings.schema.migration_requested',
      'settings.scim.token_created',
      'settings.sso.config_changed',
      'settings.upgrade.completed',
      'settings.upgrade.promoted',
      'settings.upgrade.rolled_back',
      'settings.upgrade.scheduled',
      'settings.user.accepted',
      'settings.user.created_with_password',
      'settings.user.deactivated',
      'settings.user.invitation_resent',
      'settings.user.invited',
      'settings.user.reactivated',
      'settings.warehouse.deactivated',
      'settings.warehouse.storage_rules_updated',
      'shipment.created',
      'shipping.bol.issued',
      'shipping.pick.completed',
      'shipping.pick.released',
      'shipping.shipment.confirmed',
      'shipping.shipment.packed',
      'shipping.so.cancelled',
      'shipping.so.confirmed',
      'shipping.so.released',
      'spare.reorder_threshold_breached',
      'technical.factory_spec.approved',
      'tenant.cohort.advanced',
      'tenant.migration.run',
      'tenant.migration.run.failed',
      'transfer_order.in_transit',
      'transfer_order.received',
      'transfer_order.shipped',
      'transport_lane.created',
      'transport_lane_rate_card.activated',
      'unit_of_measure.conversion_created',
      'unit_of_measure.created',
      'unit_of_measure.soft_deleted',
      'user.invited',
      'warehouse.grn.received',
      'warehouse.lp.received',
      'warehouse.lp.shipped',
      'warehouse.lp.transitioned',
      'warehouse.material.consumed',
      'wo.ready'
    )
  );

comment on constraint outbox_events_event_type_check on public.outbox_events
  is 'Regenerated from events.enum.ts DB_EVENT_TYPES (181 types; adds settings.user.created_with_password).';
