-- Migration 482 (W17 / N-42): durable gate-approval project refs + npd.project.deleted outbox.
--
-- gate_approvals.project_id is SET NULL on npd_projects delete (mig 085). Stamp
-- project_code + project_id_snapshot before delete so audit survives. Allow-list
-- npd.project.deleted so deletion events are recorded atomically with the delete.

alter table public.gate_approvals
  add column if not exists project_code text,
  add column if not exists project_id_snapshot uuid;

update public.gate_approvals ga
   set project_code = p.code,
       project_id_snapshot = p.id
  from public.npd_projects p
 where ga.project_id = p.id
   and ga.org_id = p.org_id
   and ga.project_code is null;

alter table public.outbox_events
  drop constraint if exists outbox_events_event_type_check;

alter table public.outbox_events
  add constraint outbox_events_event_type_check check (
    event_type in (
      'audit.recorded',
      'bom.initial_version_created',
      'bom.version_submitted',
      'brief.completed_for_project',
      'brief.converted',
      'brief.created',
      'catch_weight.variance_exceeded',
      'compliance_doc.deleted',
      'compliance_doc.expired',
      'compliance_doc.expiring',
      'compliance_doc.uploaded',
      'd365.cache.refreshed',
      'fa.built',
      'fa.built_reset',
      'fa.cascade',
      'fa.core_closed',
      'fa.deleted',
      'fa.dept_closed',
      'fa.dept_reopened',
      'fa.recipe_changed',
      'fa.template_applied',
      'finance.consumption.valued',
      'finance.cost_per_kg.changed',
      'finance.standard_cost.approved',
      'finance.valuation.closed_monthly',
      'finance.variance.computed',
      'finance.wac.underflow',
      'fg.allergens_changed',
      'fg.bom.released',
      'fg.created',
      'fg.edit',
      'fg.intermediate_code_changed',
      'fg.release_blocked',
      'fg.released_to_factory',
      'formulation.locked',
      'formulation.submitted_for_trial',
      'lp.received',
      'manufacturing_operations.created',
      'manufacturing_operations.deactivated',
      'manufacturing_operations.reset_to_seed',
      'manufacturing_operations.updated',
      'npd.allergens.bulk_rebuild_completed',
      'npd.builder.released_records_created',
      'npd.fg_candidate_mapped',
      'npd.gate.advanced',
      'npd.gate.approved',
      'npd.gate.reverted',
      'npd.project.brief_mapped',
      'npd.project.created',
      'npd.project.deleted',
      'npd.project.legacy_stages_closed',
      'npd.project.release_requested',
      'onboarding.first_wo_recorded',
      'quality.atp_swab_failed',
      'quality.hold.created',
      'quality.hold.released',
      'quality.ncr.opened',
      'quality.ncr.submitted',
      'quality.ncr.assigned',
      'quality.ncr.updated',
      'quality.ncr.closed',
      'quality.ncr.critical_dual_signed',
      'onboarding.step.advance',
      'onboarding.step.back',
      'onboarding.step.jump',
      'onboarding.step.restart',
      'onboarding.step.skip',
      'org.created',
      'org.mfa_enrollment.forced',
      'org.security_policy.updated',
      'planning.mrp.completed',
      'planning.schedule.published',
      'scheduler.run.completed',
      'scheduler.assignment.approved',
      'scheduler.assignment.overridden',
      'scheduler.assignment.rejected',
      'scheduler.assignment.bulk_approved',
      'matrix.version.published',
      'production.allergen_changeover.validated',
      'production.changeover.signed',
      'production.consume.blocked',
      'production.consume.completed',
      'production.downtime.recorded',
      'production.oee.snapshot',
      'production.output.recorded',
      'production.waste.recorded',
      'production.wo.closed',
      'production.wo.completed',
      'production.wo.started',
      'quality.recorded',
      'reference.allergens_added_by_process.bulk_changed',
      'reference.allergens_by_rm.bulk_changed',
      'reference.csv.committed',
      'reference.row.soft_deleted',
      'reference.row.upserted',
      'reporting.export.completed',
      'reporting.export.failed',
      'reporting.mv.refresh_completed',
      'reporting.schedule.run_completed',
      'risk.created',
      'role.assigned',
      'rule.deployed',
      'settings.core_flag.updated',
      'settings.d365_sync.updated',
      'settings.dept_override.updated',
      'settings.ip_allowlist.changed',
      'settings.line.upserted',
      'settings.location.deleted',
      'settings.location.imported',
      'settings.location.upserted',
      'settings.machine.upserted',
      'settings.module.disabled',
      'settings.module.enabled',
      'settings.module.toggled',
      'settings.notification_channel_updated',
      'settings.notification_digest_updated',
      'settings.notification_rule_updated',
      'settings.org.created',
      'settings.org.updated',
      'settings.reference.row_updated',
      'settings.role.assigned',
      'settings.rule_variant.updated',
      'settings.rule.deployed',
      'settings.schema.migration_requested',
      'settings.scim.token_created',
      'settings.sso.config_changed',
      'settings.upgrade.completed',
      'settings.upgrade.promoted',
      'settings.upgrade.rolled_back',
      'settings.upgrade.scheduled',
      'settings.user.accepted',
      'settings.user.created_with_password',
      'settings.user.deactivated',
      'settings.user.invitation_resent',
      'settings.user.invited',
      'settings.user.reactivated',
      'settings.warehouse.deactivated',
      'settings.warehouse.storage_rules_updated',
      'shipment.created',
      'shipping.so.released',
      'shipping.so.confirmed',
      'shipping.so.cancelled',
      'shipping.pick.released',
      'shipping.pick.completed',
      'shipping.shipment.packed',
      'shipping.shipment.confirmed',
      'shipping.bol.issued',
      'technical.factory_spec.approved',
      'wip.definition.updated',
      'tenant.cohort.advanced',
      'tenant.migration.run',
      'tenant.migration.run.failed',
      'unit_of_measure.conversion_created',
      'unit_of_measure.created',
      'unit_of_measure.soft_deleted',
      'user.invited',
      'transfer_order.shipped',
      'transfer_order.in_transit',
      'transfer_order.received',
      'transport_lane.created',
      'transport_lane_rate_card.activated',
      'warehouse.grn.received',
      'warehouse.lp.received',
      'warehouse.lp.transitioned',
      'warehouse.material.consumed',
      'warehouse.lp.shipped',
      'maintenance.pm.due',
      'maintenance.mwo.created',
      'maintenance.mwo.completed',
      'maintenance.loto.applied',
      'maintenance.loto.released',
      'maintenance.calibration.completed',
      'maintenance.calibration.failed',
      'maintenance.sanitation.allergen_change.completed',
      'spare.reorder_threshold_breached',
      'oee.snapshot.refreshed',
      'oee.dsl_rule.updated',
      'oee.shift.aggregated',
      'oee.alert.threshold_breached',
      'oee.anomaly.detected',
      'wo.ready',
      'fa.created',
      'fa.allergens_changed',
      'fa.intermediate_code_changed',
      'fa.edit'
    )
  );

comment on constraint outbox_events_event_type_check on public.outbox_events
  is 'Regenerated from events.enum.ts DB_EVENT_TYPES (adds npd.project.deleted).';

comment on column public.gate_approvals.project_code
  is 'Durable NPD project code retained after project_id is SET NULL on delete.';
comment on column public.gate_approvals.project_id_snapshot
  is 'Immutable NPD project id stamped before delete for audit traceability.';

