import type { AppModuleDefinition, AppModuleId } from "./types";

const RBAC_TODO = "UI-128 keeps navigation ungated; wire permission_key in the future RBAC module.";

export const APP_MODULES = [
  {
    id: "foundation",
    label: "Foundation",
    i18n_key: "navigation.app.modules.foundation",
    route: null,
    icon: "▣",
    module_kind: "platform",
    shell_kind: "platform",
    nav_exposure: "platform_only",
    nav_group: null,
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "settings",
    label: "Settings",
    i18n_key: "navigation.app.items.settings",
    route: "/settings/profile",
    icon: "⚙",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "core",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "npd",
    label: "NPD",
    i18n_key: "navigation.app.items.npd",
    route: "/npd",
    icon: "★",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "premium",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "technical",
    label: "Technical",
    i18n_key: "navigation.app.items.technical",
    route: "/technical",
    icon: "▦",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "core",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "planning-basic",
    label: "Planning",
    i18n_key: "navigation.app.items.planning",
    route: "/planning",
    icon: "▤",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "operations",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "warehouse",
    label: "Warehouse",
    i18n_key: "navigation.app.items.warehouse",
    route: "/warehouse",
    icon: "▥",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "operations",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "scanner",
    label: "Scanner",
    i18n_key: "navigation.app.modules.scanner",
    route: "/scanner",
    icon: "📱",
    module_kind: "business",
    shell_kind: "scanner",
    nav_exposure: "scanner_shell",
    nav_group: null,
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "planning-ext",
    label: "Scheduler",
    i18n_key: "navigation.app.items.scheduler",
    route: "/scheduler",
    icon: "⧗",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "operations",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "production",
    label: "Production",
    i18n_key: "navigation.app.items.production",
    route: "/production",
    icon: "⚒",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "operations",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "quality",
    label: "Quality",
    i18n_key: "navigation.app.items.quality",
    route: "/quality",
    icon: "✓",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "qa-shipping",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "finance",
    label: "Finance",
    i18n_key: "navigation.app.items.finance",
    route: "/finance",
    icon: "$",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "premium",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "shipping",
    label: "Shipping",
    i18n_key: "navigation.app.items.shipping",
    route: "/shipping",
    icon: "→",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "qa-shipping",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "reporting",
    label: "Reporting",
    i18n_key: "navigation.app.items.reporting",
    route: "/reporting",
    icon: "▧",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "analytics-network",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "maintenance",
    label: "Maintenance",
    i18n_key: "navigation.app.items.maintenance",
    route: "/maintenance",
    icon: "🔧",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "premium",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "multi-site",
    label: "Multi-Site",
    i18n_key: "navigation.app.items.multiSite",
    route: "/multi-site",
    icon: "❖",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "analytics-network",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "oee",
    label: "OEE",
    i18n_key: "navigation.app.items.oee",
    route: "/oee",
    icon: "◉",
    module_kind: "business",
    shell_kind: "desktop",
    nav_exposure: "desktop_sidebar",
    nav_group: "premium",
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
] as const satisfies readonly AppModuleDefinition[];

export const APP_MODULE_IDS = APP_MODULES.map((module) => module.id) as AppModuleId[];

export function getAppModule(moduleId: AppModuleId): AppModuleDefinition {
  const module = APP_MODULES.find((candidate) => candidate.id === moduleId);

  if (!module) {
    throw new Error(`Unknown app module: ${moduleId}`);
  }

  return module;
}
