import type { AppModuleDefinition, AppModuleId } from "./types";

const RBAC_TODO = "UI-128 keeps navigation ungated; wire permission_key in the future RBAC module.";

export const MODULE_PERMISSION_KEYS = {
  settings: "settings.org.read",
  technical: "technical.sensory.read", // No module-level technical read exists; this is the only technical.* read string.
  npd: "npd.dashboard.view",
  "planning-basic": "scheduler.run.read", // No planning-basic read string exists; use the basic planning/scheduler read gate.
  warehouse: "warehouse.inventory.read",
  scanner: "warehouse.inventory.read", // Scanner has no scanner.* enum family; inventory read is the basic warehouse/scanner data gate.
  "planning-ext": "scheduler.run.read",
  production: "production.oee.read", // No production dashboard read string exists; production.oee.read is the existing read-level production gate.
  quality: "quality.dashboard.view",
  finance: "fin.costs.read",
  shipping: "ship.dashboard.view",
  reporting: "rpt.dashboard.view",
  maintenance: "mnt.asset.read",
  "multi-site": "multi_site.site.view",
  oee: "oee.dashboard.read",
} as const satisfies Partial<Record<AppModuleId, AppModuleDefinition["permission_key"]>>;

export const APP_MODULES = [
  {
    id: "foundation",
    label: "Foundation",
    i18n_key: "Navigation.app.modules.foundation",
    route: null,
    icon_token: "▣",
    module_kind: "platform",
    shell_kind: "none",
    nav_exposure: "excluded",
    merged_into: null,
    nav_group: null,
    count_slot: null,
    permission_key: null,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "settings",
    label: "Settings",
    i18n_key: "Navigation.app.items.settings",
    route: "/settings",
    icon_token: "⚙",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "core",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.settings,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "npd",
    label: "NPD",
    i18n_key: "Navigation.app.items.npd",
    // Landing = Projects (pipeline), matching the prototype default route
    // (prototypes/design/Monopilot Design System/npd/app.jsx:29-37).
    route: "/pipeline",
    icon_token: "★",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "premium",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.npd,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "technical",
    label: "Technical",
    i18n_key: "Navigation.app.items.technical",
    route: "/technical",
    icon_token: "▦",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "premium",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.technical,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "planning-basic",
    label: "Planning",
    i18n_key: "Navigation.app.items.planning",
    route: "/planning",
    icon_token: "▤",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "operations",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS["planning-basic"],
    rbac_todo: RBAC_TODO,
  },
  {
    id: "warehouse",
    label: "Warehouse",
    i18n_key: "Navigation.app.items.warehouse",
    route: "/warehouse",
    icon_token: "▥",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "operations",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.warehouse,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "scanner",
    label: "Scanner",
    i18n_key: "Navigation.app.modules.scanner",
    route: null,
    icon_token: "📱",
    module_kind: "scanner",
    shell_kind: "scanner",
    nav_exposure: "excluded",
    merged_into: null,
    nav_group: null,
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.scanner,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "planning-ext",
    label: "Scheduler",
    i18n_key: "Navigation.app.items.scheduler",
    route: "/scheduler",
    icon_token: "⧗",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "operations",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS["planning-ext"],
    rbac_todo: RBAC_TODO,
  },
  {
    id: "production",
    label: "Production",
    i18n_key: "Navigation.app.items.production",
    route: "/production",
    icon_token: "⚒",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "operations",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.production,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "quality",
    label: "Quality",
    i18n_key: "Navigation.app.items.quality",
    route: "/quality",
    icon_token: "✓",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "qa-shipping",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.quality,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "finance",
    label: "Finance",
    i18n_key: "Navigation.app.items.finance",
    route: "/finance",
    icon_token: "$",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "premium",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.finance,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "shipping",
    label: "Shipping",
    i18n_key: "Navigation.app.items.shipping",
    route: "/shipping",
    icon_token: "→",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "qa-shipping",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.shipping,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "reporting",
    label: "Reporting",
    i18n_key: "Navigation.app.items.reporting",
    route: "/reporting",
    icon_token: "▧",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "analytics-network",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.reporting,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "maintenance",
    label: "Maintenance",
    i18n_key: "Navigation.app.items.maintenance",
    route: "/maintenance",
    icon_token: "🔧",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "premium",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.maintenance,
    rbac_todo: RBAC_TODO,
  },
  {
    id: "multi-site",
    label: "Multi-Site",
    i18n_key: "Navigation.app.items.multiSite",
    route: "/multi-site",
    icon_token: "❖",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "analytics-network",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS["multi-site"],
    rbac_todo: RBAC_TODO,
  },
  {
    id: "oee",
    label: "OEE",
    i18n_key: "Navigation.app.items.oee",
    route: "/oee",
    icon_token: "◉",
    module_kind: "desktop",
    shell_kind: "app",
    nav_exposure: "sidebar",
    merged_into: null,
    nav_group: "premium",
    count_slot: null,
    permission_key: MODULE_PERMISSION_KEYS.oee,
    rbac_todo: RBAC_TODO,
  },
] as const satisfies readonly AppModuleDefinition[];

export const APP_MODULE_IDS = APP_MODULES.map((module) => module.id) as AppModuleId[];

export function getAppModule(moduleId: AppModuleId): AppModuleDefinition {
  const module = APP_MODULES.find((candidate) => candidate.id === moduleId);

  if (!module) {
    throw new Error(`Unknown app module: ${moduleId}`);
  }

  return module;
}
