export type Eu14AllergenSeed = {
  allergenCode: string;
  allergenName: string;
  displayName: string;
  regulatoryFramework: 'EU_FIC_1169_2011';
  seedSource: 'EU14_default';
  displayNamePl: string;
  displayNameUk: string;
  displayNameRo: string;
  marker: '[UNIVERSAL]';
};

export const eu14Allergens: readonly Eu14AllergenSeed[] = [
  {
    allergenCode: 'gluten',
    allergenName: 'Cereals containing gluten',
    displayName: 'Gluten',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Gluten',
    displayNameUk: 'Глютен',
    displayNameRo: 'Gluten',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'crustaceans',
    allergenName: 'Crustaceans',
    displayName: 'Crustaceans',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Skorupiaki',
    displayNameUk: 'Ракоподібні',
    displayNameRo: 'Crustacee',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'eggs',
    allergenName: 'Eggs',
    displayName: 'Eggs',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Jaja',
    displayNameUk: 'Яйця',
    displayNameRo: 'Ouă',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'fish',
    allergenName: 'Fish',
    displayName: 'Fish',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Ryby',
    displayNameUk: 'Риба',
    displayNameRo: 'Pește',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'peanuts',
    allergenName: 'Peanuts',
    displayName: 'Peanuts',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Orzeszki ziemne',
    displayNameUk: 'Арахіс',
    displayNameRo: 'Arahide',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'soybeans',
    allergenName: 'Soybeans',
    displayName: 'Soybeans',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Soja',
    displayNameUk: 'Соя',
    displayNameRo: 'Soia',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'milk',
    allergenName: 'Milk',
    displayName: 'Milk',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Mleko',
    displayNameUk: 'Молоко',
    displayNameRo: 'Lapte',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'nuts',
    allergenName: 'Nuts',
    displayName: 'Nuts',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Orzechy',
    displayNameUk: 'Горіхи',
    displayNameRo: 'Fructe cu coajă lemnoasă',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'celery',
    allergenName: 'Celery',
    displayName: 'Celery',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Seler',
    displayNameUk: 'Селера',
    displayNameRo: 'Țelină',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'mustard',
    allergenName: 'Mustard',
    displayName: 'Mustard',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Gorczyca',
    displayNameUk: 'Гірчиця',
    displayNameRo: 'Muștar',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'sesame',
    allergenName: 'Sesame seeds',
    displayName: 'Sesame',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Sezam',
    displayNameUk: 'Кунжут',
    displayNameRo: 'Susan',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'sulphites',
    allergenName: 'Sulphur dioxide and sulphites',
    displayName: 'Sulphites',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Dwutlenek siarki i siarczyny',
    displayNameUk: 'Діоксид сірки та сульфіти',
    displayNameRo: 'Dioxid de sulf și sulfiți',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'lupin',
    allergenName: 'Lupin',
    displayName: 'Lupin',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Łubin',
    displayNameUk: 'Люпин',
    displayNameRo: 'Lupin',
    marker: '[UNIVERSAL]',
  },
  {
    allergenCode: 'molluscs',
    allergenName: 'Molluscs',
    displayName: 'Molluscs',
    regulatoryFramework: 'EU_FIC_1169_2011',
    seedSource: 'EU14_default',
    displayNamePl: 'Mięczaki',
    displayNameUk: 'Moluște',
    displayNameRo: 'Moluște',
    marker: '[UNIVERSAL]',
  },
] as const;
